### ISSUE TITLE
Fails with missing "shell integration" field on Nushell 0.93.1

### ISSUE THREAD

**Issue by kubouch** [amtoine/nu_plugin_explore#64]
related to
- https://github.com/nushell/nushell/pull/12629

I get this error on Nushell 0.93.1 (latest main):
```
> $nu | nu_plugin_explore
Plugin `explore` error: Plugin failed to decode: missing field `shell_integration`
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: missing field `shell_integration`
```

## `version | transpose key value | to md --pretty`
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | bf07806b1bc96eebcaa57456c97035a6bce68ef7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-24 09:44:08 +03:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | formats, gstat, highlight, inc, polars, query   |

**Comment by amtoine** [comment]
thanks for reporting, i can actually reproduce this with nushell/nushell@ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1

**Comment by amtoine** [comment]
ok, it's working with Nushell 0.93.0, so something happened in Nushell between nushell/nushell@3b220e07e and nushell/nushell@ac4125f8e

**Comment by amtoine** [comment]
bisecting Nushell... :recycle: 

so looong to compile on my personal machine :skull:

**Comment by amtoine** [comment]
okey, found the culprit:
- https://github.com/nushell/nushell/pull/12629

**Comment by amtoine** [comment]
i was able to fix the issue by compiling the plugin with the same revision as my Nushell install, i.e. nushell/nushell@ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1, and the following TOML
```toml
nuon = { git = "https://github.com/nushell/nushell", rev = "ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1", package = "nuon" }
nu-plugin = { git = "https://github.com/nushell/nushell", rev = "ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1", package = "nu-plugin" }
nu-protocol = { git = "https://github.com/nushell/nushell", rev = "ac4125f8edd5b8f3f68aa653d03d57b2d25f1da1", package = "nu-protocol", features = ["plugin"] }
```
instead of
```toml
nuon = "0.93.0"
nu-plugin = "0.93.0"
nu-protocol = "0.93.0"
```

@kubouch, could you try with the same `rev` as the output of `(version).commit_hash`? :innocent:
